# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/authentication_type.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n protos/authentication_type.proto\x12\x1d\x63om.sqream.cloud.generated.v1*x\n\x12\x41uthenticationType\x12#\n\x1f\x41UTHENTICATION_TYPE_UNSPECIFIED\x10\x00\x12 \n\x1c\x41UTHENTICATION_TYPE_INTERNAL\x10\x01\x12\x1b\n\x17\x41UTHENTICATION_TYPE_IDP\x10\x02\x42\x02P\x01\x62\x06proto3')

_AUTHENTICATIONTYPE = DESCRIPTOR.enum_types_by_name['AuthenticationType']
AuthenticationType = enum_type_wrapper.EnumTypeWrapper(_AUTHENTICATIONTYPE)
AUTHENTICATION_TYPE_UNSPECIFIED = 0
AUTHENTICATION_TYPE_INTERNAL = 1
AUTHENTICATION_TYPE_IDP = 2


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _AUTHENTICATIONTYPE._serialized_start=67
  _AUTHENTICATIONTYPE._serialized_end=187
# @@protoc_insertion_point(module_scope)
