# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/client_info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/client_info.proto\x12\x1d\x63om.sqream.cloud.generated.v1\"\x1d\n\nClientInfo\x12\x0f\n\x07version\x18\x01 \x01(\tB\x02P\x01\x62\x06proto3')



_CLIENTINFO = DESCRIPTOR.message_types_by_name['ClientInfo']
ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'protos.client_info_pb2'
  # @@protoc_insertion_point(class_scope:com.sqream.cloud.generated.v1.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _CLIENTINFO._serialized_start=59
  _CLIENTINFO._serialized_end=88
# @@protoc_insertion_point(module_scope)
