# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/client_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/client_info.proto\x12\x1d\x63om.sqream.cloud.generated.v1\"]\n\nClientInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12>\n\x0bsource_type\x18\x02 \x01(\x0e\x32).com.sqream.cloud.generated.v1.SourceType*t\n\nSourceType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x12\n\x0e\x42LUE_UI_SYSTEM\x10\x01\x12\x10\n\x0c\x42LUE_UI_USER\x10\x02\x12\x07\n\x03\x43LI\x10\x03\x12\x08\n\x04JOBS\x10\x04\x12\x0e\n\nSTATISTICS\x10\x05\x12\x0c\n\x08\x45XTERNAL\x10\x06\x42\x02P\x01\x62\x06proto3')

_SOURCETYPE = DESCRIPTOR.enum_types_by_name['SourceType']
SourceType = enum_type_wrapper.EnumTypeWrapper(_SOURCETYPE)
UNSPECIFIED = 0
BLUE_UI_SYSTEM = 1
BLUE_UI_USER = 2
CLI = 3
JOBS = 4
STATISTICS = 5
EXTERNAL = 6


_CLIENTINFO = DESCRIPTOR.message_types_by_name['ClientInfo']
ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'protos.client_info_pb2'
  # @@protoc_insertion_point(class_scope:com.sqream.cloud.generated.v1.ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _SOURCETYPE._serialized_start=154
  _SOURCETYPE._serialized_end=270
  _CLIENTINFO._serialized_start=59
  _CLIENTINFO._serialized_end=152
# @@protoc_insertion_point(module_scope)
